language: php

php:
  - 5.3
  - 5.4

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev

notifications:
  email:
    recipients:
      - technical@savvycreativeuk.com
    on_success: [never]
    on_failure: [always]