<?php

namespace Savvy\PagesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends EntityRepository
{

    public function getPageContents($page_id)
    {
        return $this->createQueryBuilder('c')
                ->leftJoin("c.page", "p")
                ->leftJoin("c.field", "f")
                ->where("p.id = :page_id")
                ->setParameter("page_id", $page_id)
                ->orderBy("f.name", "ASC")
                ->getQuery()
                ->getResult();
    }

}