<?php

namespace Savvy\PagesBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryMediaRepository extends EntityRepository
{

    public function getConstructionGalleries($development_id, $offset)
    {
        return $this->createQueryBuilder('gm')
            ->select("gm, md")
            ->innerJoin("gm.gallery_data", "gd")
            ->innerJoin("gd.development", "d")
            ->innerJoin("gm.media_data", "md")
            ->innerJoin("gd.gallery_type", "gt")
            ->where("d.id = :development AND gt.name = :construction")
            ->setParameter("development", $development_id)
            ->setParameter("construction", "construction")
            ->setMaxResults(5)
            ->setFirstResult($offset)
            ->getQuery()
            ->getResult();
    }

}