<?php

namespace Savvy\PagesBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Savvy\PagesBundle\Utility\Utility;

/**
 * MediaPathRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaPathRepository extends EntityRepository {

}